### PR TITLE
feat: move images to icr.io/ext/sysdig registry/repo

### PR DESCRIPTION
**Pull request by ctolon22**
### Description

Moving images to the managed ICR repository where all Monitoring/Workload Protection components are uploaded

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
Can you also update the helm chart location on line 31?

**Comment by ctolon22** [comment]
Added in the latest commit.

**Comment by ocofaigh** [comment]
Need to get https://github.com/terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent/pull/137 merged first to unblocked tests for this PR

**Comment by ocofaigh** [comment]
@ctolon22 can you rebase with main now - above PR is merged and pipeline unblocked

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
